### ISSUE TITLE
[feature request] Sort array

### ISSUE THREAD

**Issue by geslotencirkel** [mgunyho/PdArray#11]
after recording a sequence of values, it would be helpful to sort from greatest to lowest - then allowing you to remap a controller to step values and output the values from the PdArray sequence

**Comment by mgunyho** [comment]
Hmm, I'm not entirely sure I see how the sorting would be useful, can you give an example of how you would use it? I also don't completely understand what you mean by "remap a controller to step values".

It would be pretty simple to implement as an option in the right-click menu, so I might consider it. If you were thinking that the sort could be triggered by a CV signal, I don't think that can fit on the front panel.

**Comment by geslotencirkel** [comment]
Hi, if I have a map for a keyboard controller that just increments steps per note, it would be simple to create scales in PdArray and just use it to pump out recorded values in some ascending order for example. Otherwise their is a lot of remapping and trial and error to correctly map a scale.

**Comment by mgunyho** [comment]
Okay, I think see your idea, although it sounds quite specific. I've added a sort option to the right-click menu, it will be available in v1.0.5 soon.
