### ISSUE TITLE
LOAD wav file causes crash sometimes

### ISSUE THREAD

**Issue by vcvrackideas** [mgunyho/PdArray#13]
Hi! Load wav with change of the length works ok but when I tried to use just load wav file on some samples there was an immediately crash of the Rack.

**Comment by mgunyho** [comment]
Hi, thanks for the report. Can you copy the contents of the Rack/log.txt after a crash here, inside triple backticks, like this:
````
```
< insert crash log here >
```
````
Is it possible for you to send me a sample that causes a crash? Or can you identify how it differs from other samples that don't cause a crash?

**Comment by mgunyho** [comment]
This has now been fixed. It will be available in v1.0.6, which will be released hopefully soon.
