### ISSUE TITLE
Samples modified just after recording

### ISSUE THREAD

**Issue by nesdnuma** [mgunyho/PdArray#18]
Hello,

I am trying to record a single cycle waveform into Array. While recording everything seems to be fine, the waveform is drawn as expected. However after completion some values are modified because of an unknown reason. 

You can check with the patcher below (tested in Rack 2.0.6).

![image](https://user-images.githubusercontent.com/6513218/151168181-35cb9756-7790-4c85-a2bf-99b3c1ea7896.png)

**Comment by mgunyho** [comment]
Hi, thanks for the report.

Which module are you using ther as the envelope generator? I suspect that even though the "decay" is set to zero, it takes some non-zero time to return when it's finished. This might cause this issue. Try the same patch with the Miniramp module included with PdArray, like this:

![pdarray-envelope](https://user-images.githubusercontent.com/20118130/151417760-6f022295-c055-469f-9c37-83169e4e71a1.png)

As a bonus, you don't need to use the extra formula module for the record enable gate.

**Comment by nesdnuma** [comment]
This functions indeed. Thanks a lot!
