### ISSUE TITLE
Compile crashes on Windows 10

### ISSUE THREAD

**Issue by caecos** [mgunyho/PdArray#3]
$ RACK_DIR=C:/msys64/Rack-SDK make
g++  -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Miniramp.cpp.o src/Miniramp.cpp
g++  -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/plugin.cpp.o src/plugin.cpp
g++  -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Array.cpp.o src/Array.cpp
src/Array.cpp: In member function 'void Array::loadSample(std::string)':
src/Array.cpp:148:75: error: no matching function for call to 'min(long unsigned int, std::vector<float>::size_type)'
  148 |   int newSize = std::min((unsigned long) totalPCMFrameCount, buffer.size());
      |                                                                           ^
In file included from C:/msys64/mingw64/include/c++/9.2.0/bits/char_traits.h:39,
                 from C:/msys64/mingw64/include/c++/9.2.0/string:40,
                 from C:/msys64/Rack-SDK/include/common.hpp:15,
                 from C:/msys64/Rack-SDK/include/rack.hpp:4,
                 from src/plugin.hpp:1,
                 from src/Array.cpp:1:
C:/msys64/mingw64/include/c++/9.2.0/bits/stl_algobase.h:198:5: note: candidate: 'template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)'
  198 |     min(const _Tp& __a, const _Tp& __b)
      |     ^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/stl_algobase.h:198:5: note:   template argument deduction/substitution failed:
src/Array.cpp:148:75: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'std::vector<float>::size_type' {aka 'long long unsigned int'})
  148 |   int newSize = std::min((unsigned long) totalPCMFrameCount, buffer.size());
      |                                                                           ^
In file included from C:/msys64/mingw64/include/c++/9.2.0/bits/char_traits.h:39,
                 from C:/msys64/mingw64/include/c++/9.2.0/string:40,
                 from C:/msys64/Rack-SDK/include/common.hpp:15,
                 from C:/msys64/Rack-SDK/include/rack.hpp:4,
                 from src/plugin.hpp:1,
                 from src/Array.cpp:1:
C:/msys64/mingw64/include/c++/9.2.0/bits/stl_algobase.h:246:5: note: candidate: 'template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)'
  246 |     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/stl_algobase.h:246:5: note:   template argument deduction/substitution failed:
src/Array.cpp:148:75: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'std::vector<float>::size_type' {aka 'long long unsigned int'})
  148 |   int newSize = std::min((unsigned long) totalPCMFrameCount, buffer.size());
      |                                                                           ^
In file included from C:/msys64/mingw64/include/c++/9.2.0/algorithm:62,
                 from C:/msys64/Rack-SDK/include/math.hpp:4,
                 from C:/msys64/Rack-SDK/include/rack.hpp:5,
                 from src/plugin.hpp:1,
                 from src/Array.cpp:1:
C:/msys64/mingw64/include/c++/9.2.0/bits/stl_algo.h:3444:5: note: candidate: 'template<class _Tp> _Tp std::min(std::initializer_list<_Tp>)'
 3444 |     min(initializer_list<_Tp> __l)
      |     ^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/stl_algo.h:3444:5: note:   template argument deduction/substitution failed:
src/Array.cpp:148:75: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
  148 |   int newSize = std::min((unsigned long) totalPCMFrameCount, buffer.size());
      |                                                                           ^
In file included from C:/msys64/mingw64/include/c++/9.2.0/algorithm:62,
                 from C:/msys64/Rack-SDK/include/math.hpp:4,
                 from C:/msys64/Rack-SDK/include/rack.hpp:5,
                 from src/plugin.hpp:1,
                 from src/Array.cpp:1:
C:/msys64/mingw64/include/c++/9.2.0/bits/stl_algo.h:3450:5: note: candidate: 'template<class _Tp, class _Compare> _Tp std::min(std::initializer_list<_Tp>, _Compare)'
 3450 |     min(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
C:/msys64/mingw64/include/c++/9.2.0/bits/stl_algo.h:3450:5: note:   template argument deduction/substitution failed:
src/Array.cpp:148:75: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
  148 |   int newSize = std::min((unsigned long) totalPCMFrameCount, buffer.size());
      |                                                                           ^
src/Array.cpp: In member function 'virtual void NumberTextField::onSelectKey(const rack::event::SelectKey&)':
src/Array.cpp:441:23: warning: comparison of integer expressions of different signedness: 'std::__cxx11::basic_string<char>::size_type' {aka 'long long unsigned int'} and 'int' [-Wsign-compare]
  441 |     if(newText.size() > pasteLength) newText.erase(pasteLength);
      |        ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
src/Array.cpp: In member function 'virtual void NumberTextField::onSelectText(const rack::event::SelectText&)':
src/Array.cpp:462:18: warning: comparison of integer expressions of different signedness: 'std::__cxx11::basic_string<char>::size_type' {aka 'long long unsigned int'} and 'int' [-Wsign-compare]
  462 |   if(text.size() < maxCharacters
      |      ~~~~~~~~~~~~^~~~~~~~~~~~~~~
make: *** [C:/msys64/Rack-SDK/compile.mk:62: build/src/Array.cpp.o] Error 1

**Comment by mgunyho** [comment]
Oh man, looks like every platform has different opinions about the types of those two variables. Does it work if you try again with https://github.com/mgunyho/PdArray/commit/bf7d42089c514f601e2a3e15679e3fb2fd3d9266 ?

**Comment by mgunyho** [comment]
The plugin has now been approved to the plugin library so I assume this issue has been fixed.
