### ISSUE TITLE
Feature request: change size with right-click

### ISSUE THREAD

**Issue by nesdnuma** [mgunyho/PdArray#4]
Hello,

Nice module.

I suggest to add the possibility to change the size with a right-click as it exists for all potentiometers in Rack.

**Comment by mgunyho** [comment]
Do you mean that right-clicking on the size display would open a dialog box like for the potentiometers? Isn't it enough that it works with the left click?

**Comment by nesdnuma** [comment]
When one wants to enter a specific value with the keyboard, right-click within a dialog box seems the usual way to do it, so it's just that the current way seems a bit weird.

**Comment by mgunyho** [comment]
I could make it so that right-clicking on the size display also enters the edit mode, would that be alright? I think having the dialog box in addition to the display would be odd, and it would also be an additional hassle to check for the maximum number of allowed digits.

**Comment by nesdnuma** [comment]
Good idea!

**Comment by mgunyho** [comment]
Done, it was a bit uglier than I thought since the left click is handled outside widget events. It might take a while before this shows up in the plugin manager, I don't want to release an update until I have enough changes.
