### ISSUE TITLE
Rreset typo in right-click menu array contents

### ISSUE THREAD

**Issue by Petervos2018** [mgunyho/PdArray#5]
As seen here.

![Rreset](https://user-images.githubusercontent.com/46076474/67165144-c69cb400-f381-11e9-930e-a311503290cd.png)

Thanks for the modules

Peter.

**Comment by mgunyho** [comment]
Thanks! I'll probably not bother Andrew with this until I have some bigger updates to the module, so it might not appear in the library version for a while.
