### ISSUE TITLE
Feature request: PdArray with STEP input rather than POS input

### ISSUE THREAD

**Issue by clone45** [mgunyho/PdArray#6]
Hello!  I was introduced to your module when asking a question on the VCV Rack Community forums here: https://community.vcvrack.com/t/looking-for-a-sequencer-for-long-modulations/6354

Essentially, I was looking for a module that I could use for producing modulations over long periods of time, meaning 6 minutes or so.  I want to gradually evolve my songs over time.  The PdArray is the closest module that I've found so far to do what I want.  The only downfall is that the POS input is somewhat difficult to control for my purposes.  However, if there were a variant of the module that replaced the POS input with a STEP input, it would be nearly perfect!  

I say "nearly" only because it might use up a lot of memory for long tables.  Because my modulations probably will change only 20% of the time, the other 80% of the time they'll be all the same value, meaning a lot of repeating values in the table will just be taking up memory. 

An ideal module would store key/value pairs where the key would store the step number and the value would store the CV output value.  But I can probably live with that inefficiency!

Anyhow, if you're like, "Oh, yeah, I could do that in less than 45 minutes!" I would be forever grateful. :-)

Cheers,
Bret

**Comment by mgunyho** [comment]
By "STEP input", do you mean that the cursor would advance by one position when the input receives a trigger? Sounds like a reasonable use case. Array could be set to that mode from a right-click menu but that would require an additional port for the reset so I don't think I'll do it that way. What I could do instead is to create another module similar to Miniramp that could be advanced by stepping. I suspect that such a module already exists in some pack, or it shouldn't be too hard to create using e.g. VCV Prototype. I could look into this a bit later this week.

> An ideal module would store key/value pairs where the key would store the step number and the value would store the CV output value.

Array already essentially works this way, with the keys being numbers from zero to the array size, just scaled to the range 0..10 or -5..5 or -10..10 depending on the POS RANGE option.

I wouldn't worry about memory issues, using the maximum 999999 points uses around 100 mb of RAM I think, so having thousands or even tens of thousands of points is completely fine.

**Comment by mgunyho** [comment]
Reading through the forum post more carefully, I see that you perhaps want something more like a super slow version of Miniramp? There I could easily add a right-click menu option to extend the time range to several minutes, although that requires a bit of fiddling with the display that shows the duration.

**Comment by clone45** [comment]
Hello!  Thanks a ton for considering my request.  I'm not really looking
for a super slow version of Miniramp.  You had it correct before, where the
cursor would advance by one position when the STEP input receives a
trigger.  I would leave it in your capable hands as to whether this would
be a new module, or if the functionality is added to the existing PdArray.
Again, thanks for listening!!

**Comment by mgunyho** [comment]
I have now added Ministep, which can be used to step through the array, see the bottom of the README. It should show up in the plugin manager sometime soon. Thanks for the idea!

**Comment by clone45** [comment]
Thank you for implementing this!  I'm so excited!
