### ISSUE TITLE
Using PdArray as a sequencer bug

### ISSUE THREAD

**Issue by dag2099** [mgunyho/PdArray#7]
(vcv 1.1.5, windows 7 64)
I'm using a triangle wave from Frozen Wasteland BPMlfo to set the position of the output in PdArray and it doesn't seem to be changing the note at the point on the display when the line crosses the boundary between levels. Also, as the line moves beyond the center the problem is magnified. This makes it a bit difficult to use PdArray as a sequencer.

**Comment by mgunyho** [comment]
Hmm, sounds interesting. You are using the step output, not smooth, right? Could you maybe upload a minimal patch where this happens? I can look into this on the weekend.

**Comment by dag2099** [comment]
I'm using stepped, yes. I'm not allowed to upload .vcv files here so I'll put it on Patchstorage:
[https://patchstorage.com/pdarray-sequencer-bug/](https://patchstorage.com/pdarray-sequencer-bug/)
If you need me to make a video I will but it's obviously a little bit more effort.
Thx.

**Comment by mgunyho** [comment]
Thanks for pointing this out! I'll probably submit the update to the plugin library tomorrow.

**Comment by Petervos2018** [comment]
Just to tell you that it's fixed and thank you for your very useful modules,

Peter.
