### ISSUE TITLE
Ministep does not show full Max value

### ISSUE THREAD

**Issue by danhphotos** [mgunyho/PdArray#8]
Ministep lets you enter a 3 digit value for Max, but only shows first 2 digits, 3rd wraps to non-visible 2nd line of display.  For example, enter 234, only 23 shows, but it seems to use 234 as Max. Appears to function correctly, just does not display correctly.

**Comment by mgunyho** [comment]
I seem to be able to reproduce this only on certain zoom levels (50% and less), but maybe your display has a different DPI or something. Anyway, it's fixed by commit 28f56dd.

This is such a small change that maybe I will not update the version in the plugin library just yet, but it will be in the next update. Thanks!

**Comment by danhphotos** [comment]
Hey no problem, once I figured it out that it works but just displays wrong I'm fine with it, so please do not do another update just for this! This occurs for me while running Rack with zoom at 120% on Windows.

 Great module by the way, I am using it to step forwards & backwards 1 sample at a time thru the 256 samples I have loaded into the Lomas Advanced Sampler module, using AS Triggers MkII into INC & DEC. 

Thanks for the quick response!
    On Wednesday, January 22, 2020, 11:13:03 AM PST, mgunyho <notifications@github.com> wrote:  
 
 
Closed #8.

**Comment by mgunyho** [comment]
Alright, thanks for the info. I'm glad to hear you like it!

**Comment by danhphotos** [comment]
I just got the new version with the SCL input, this one does the same as the previous version: Max shows only 2 digits the 3rd wraps to 2nd row. SCL & counter both show 3 digit values. I am attaching a picture - the values should be 127, 102 and 127.

Thanks!
    On Wednesday, January 22, 2020, 9:58:05 PM PST, mgunyho <notifications@github.com> wrote:  
 
 
Alright, thanks for the info. I'm glad to hear you like it!

**Comment by mgunyho** [comment]
Ouch. I guess I can make the text box still a bit wider and hope that it fixes it. I suppose you don't have installed the tools to compile the plugin? If you did, you could try and adjust the value [here](https://github.com/mgunyho/PdArray/blob/master/src/Ministep.cpp#L406) until it no longer happens. I can also just increase it by a fairly large amount for the next update (although I'm not sure how soon that is going to happen).

I don't see the picture, are you sure it uploaded correctly?

**Comment by danhphotos** [comment]
The other 2 fields work just fine, maybe make it like them?
My compiling days are LONG past, I can't help you there.
Here is the attachment again, a file named MiniStep Displays.png
Thanks!

    On Monday, January 27, 2020, 11:25:28 AM PST, mgunyho <notifications@github.com> wrote:  
 
 
Ouch. I guess I can make the text box still a bit wider and hope that it fixes it. I suppose you don't have installed the tools to compile the plugin? If you did, you could try and adjust the value here until it no longer happens. I can also just increase it by a fairly large amount for the next update (although I'm not sure how soon that is going to happen).

I don't see the picture, are you sure it uploaded correctly?

**Comment by mgunyho** [comment]
Hello again,

I've tried to fix this again in PdArray v1.0.4, which has just been released in the library. Could you please check if the bug has been fixed for you?

**Comment by danhphotos** [comment]
Yes, all 3 displays now show 3 digits - thanks!

**Comment by danhphotos** [comment]
Yes, it works now - all 3 windows show 3 digits each. Thanks! I closed the issue.

    On Saturday, June 13, 2020, 8:01:42 AM PDT, mgunyho <notifications@github.com> wrote:  
 
 


Hello again,

I've tried to fix this again in PdArray v1.0.4, which has just been released in the library. Could you please check if the bug has been fixed for you?
